language: python
sudo: false
matrix:
    include:
        - python: 3.3
          env: TOX_ENV=py33
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
install:
    - pip install tox
    - pip install -r dev-requirements.txt
script:
    - tox -e $TOX_ENV