language: python
sudo: false
matrix:
    include:
        - python: 3.2
          env: TOX_ENV=py32
        - python: 3.3
          env: TOX_ENV=py33
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
        - python: pypy3
          env: TOX_ENV=pypy3
install:
    - pip install cffi
    - pip install tox
script:
    - tox -e $TOX_ENV